from commands.spam import SpamCog
from commands.on_message import OnMessage
from commands.games import GamesCog
from commands.on_delete import OnDelete
from commands.on_typing import OnTyping
from commands.on_command import OnCommand
from commands.on_command_error import OnCommandErrorCog
from commands.help import HelpCog
from commands.profile import ProfileCog
from commands.status import StatusCog
from commands.channel import ChannelCog
from commands.admin import AdminCog
from commands.ignore import IgnoreCog
from commands.invite import InviteCog
from commands.nick import NickCog
from commands.role import RoleCog
from commands.animated import AnimatedCog
from commands.dump import DumpCog
from commands.text import TextCog
from commands.codeblock import CodeblockCog
from commands.image import ImageCog, ImageCog2
from commands.troll import TrollCog
from commands.fun import FunCog
from commands.member import MemberCog
from commands.tools import ToolsCog
from commands.utils import UtilsCog
from commands.all import AllCog
from commands.mass import MassCog
from commands.guild import GuildCog
from commands.exploit import ExploitCog
from commands.abuse import AbuseCog
from commands.nettool import NettoolCog
from commands.privacy import PrivacyCog
from commands.protectionguild import ProtectionGuildCog
from commands.protection import ProtectionCog
from commands.whitelist import WhitelistCog
from commands.settings import SettingsCog
from commands.backups import BackupsCog
from commands.custom import CustomCog
from commands.share import ShareCog
from commands.encode import EncodeCog
from commands.decode import DecodeCog
from commands.giveaway import GiveawayCog
from commands.crypto import CryptoCog
from commands.customize import CustomizeCog
from commands.hscroller import HScrollerCog
from commands.hentai import HentaiCog
from commands.on_member import OnMember
from commands.sniper import SniperCog
from commands.theme import ThemeCog
from commands.themes import ThemesCog
from commands.communitythemes import CommunitythemesCog
from commands.toast import ToastCog
from commands.toasts import ToastsCog
from commands.webhooksetup import WebhookSetupCog
from commands.webhooks import WebhooksCog
from commands.webhookurl import WebhookUrlCog
from commands.webhook import WebhookCog
from commands.misc import MiscCog
