# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import collections
import logging
import client
import appinfo
import user
import emoji
import partial_emoji
import activity
import channel
import guild
import flags
import relationship
import member
import message
import asset
import errors
import calls
import permissions
import role
import file
import colour
import integrations
import invite
import template
import widget
import object
import reaction
import enums
import embeds
import mentions
import player
import recorder
import webhook
import voice_client
import audit_logs
import raw_models
import team
import sticker
import account
import remote_auth
import helpers
import asyncio
import datetime
import hashlib
import random
import tempfile
import discord.errors
import discord
import http
import aiohttp
import json
import math
import time
import discord.gateway
import captcha
import email
import inspect
import threading
import discord.utils
import flask
import cryptography
import base64
import discord.context_properties
import discord.http
import discord.backoff
import discord.user
import gateway
import abc
import struct
import array
import collections.abc
import unicodedata
import bisect
import operator
import re
import warnings
import platform
import subprocess
import plistlib
import winreg
import shutil

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

